version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Building the Go code...
      - java -version
      - mvn clean
artifacts:
  files:
    - '**/*'
